
### INPUT
cell_type_config: "config/config_cell_types.tsv" # L3 --> L2 --> L1 mapping; fragment files for the 15

n_iterations: 10
seed_multiplier: 13
n_sample: 30000 # about 500 cells for smallest cell type
n_L1_sample: 10000 # because it's hard to run E2G on the 30k 
model_dir_use: models/multiome_powerlaw_v3

### OUTPUT
scratch_dir: /scratch/users/shethm/scE2G_permute_and_compare
results_dir: results/2025_0220_iter10_seed13

### OUTPUT OPTIONS
benchmark_performance: False # only set to True if all clusters are K562
make_IGV_tracks: False # create ATAC bw and prediction bedpe files?

### REFERENCE FILES
gene_annotations: "resources/genome_annotations/gencode.v43.chr_patch_hapl_scaff.annotation.gtf.gz" # compatible with RNA matrix
gene_TSS500: "resources/genome_annotations/CollapsedGeneBounds.hg38.intGENCODEv43.TSS500bp.bed" # gene list with promoter bounds
genes: "resources/genome_annotations/CollapsedGeneBounds.hg38.intGENCODEv43.bed" # gene list with gene body bounds 
crispr_dataset: "resources/EPCrisprBenchmark_ensemble_data_GRCh38.intGENCODEv43.tsv.gz" # crispr training data

### SUBMODULE PARAMS 
encode_re2g_dir: "ENCODE_rE2G"
model_dir: "models/"
reference_features: ["numTSSEnhGene", "distance", "activity_base", "TargetGenePromoterActivityQuantile", "numNearbyEnhancers", "sumNearbyEnhancers", "is_ubiquitous_uniform", "P2PromoterClass", "numCandidateEnhGene", "hic_contact_pl_scaled_adj", "ABC.Score", "ABC.Numerator", "ABC.Denominator", "normalized_dhs_prom", "normalized_dhs_enh", "normalized_atac_prom", "normalized_atac_enh", "Kendall", "ARC.E2G.Score"]
final_score_col: "E2G.Score.qnorm"